### PR TITLE
fix amount input validation. Closes #26

### LINKED ISSUE #26: Blank page when typing dot(.) then follows a digit in stake amount input
image

image

### PR DESCRIPTION
**Pull request by sihoang**

### CODE REVIEW

File: packages/client/src/formatter.js [hunk 1]
```diff
@@ -15,11 +15,26 @@ export const currency = (s) =>
...
+// input 1 TRST -> output 1e6 in bigNumber
+// will throw if cannot convert
+// will throw if decimal > 6
+export const convertAmountToSmallestTRST = (s) =>
+  bigNumber(web3.utils.toWei(s.toString(), 'mwei'));
+
+// convert blockchain amount in string/bn/number to wholeTRST in number
+// input 1e6 -> output 1 TRST in number
+// cannot use bigNumber because bigNumber does not support decimal
+const convertToWholeTRST = (s) =>
```
Comment (sihoang) [inline packages/client/src/formatter.js]: export if needed in the future

File: packages/client/src/formatter.js [hunk 2]
```diff
@@ -15,11 +15,23 @@ export const currency = (s) =>
     .toFixed(2)
     .toLocaleString()}`;
 
+// does not support decimal
+// used for converting all the values from blockchain
 export const bigNumber = (s) => web3.utils.toBN(s);
 
-export const trstInBN = (s) => bigNumber(s).div(bigNumber(1e6));
```
Comment (sihoang) [inline packages/client/src/formatter.js]: this does not work if for decimal i.e cannot convert 123000 to 0.123

File: packages/client/src/formatter.js [hunk 3]
```diff
@@ -15,11 +15,23 @@ export const currency = (s) =>
...
-
-export const trst = (s) => numberString(trstInBN(s));
```
Comment (sihoang) [inline packages/client/src/formatter.js]: this does not work because it relies on trstInBN
